const zhCN = {
  'language.label': '语言', 'nav.label': '主导航', 'nav.today': '今日', 'nav.inventory': '库存', 'nav.history': '历史', 'brand.tagline': '用心做饭，一起分享', 'brand.home': '赛博厨房首页', 'household.profile': '家庭档案', 'household.members': '家庭成员',
  'status.loadTitle': '无法加载你的厨房。', 'status.retry': '重试', 'status.loading': '正在准备你的厨房…', 'status.loadingBody': '正在加载家庭档案、库存和餐点建议。', 'error.generic': '出现问题，请重试。', 'error.network': '无法连接赛博厨房，请检查网络后重试。', 'error.unreadable': '赛博厨房返回了无法读取的响应。', 'error.http': '赛博厨房返回错误（{{status}}）。', 'error.aiUnavailable': 'AI 餐点推荐暂不可用。你仍可查看和管理厨房。', 'error.aiFailed': '暂时无法生成新餐点建议。现有建议未被更改，请重试。',
  'today.morning': '早上好', 'today.afternoon': '下午好', 'today.evening': '晚上好', 'today.crew': '厨房伙伴们', 'today.easy': '让今晚的晚餐轻松一点。', 'today.synced': '库存已同步', 'today.done': '晚餐完成！', 'today.doneBody': '{{meal}} 已加入历史记录，库存也已更新。', 'today.inProgress': '进行中', 'today.readyConfirm': '等待确认', 'today.cooking': '烹饪中', 'today.feedbackWaiting': '你的反馈和库存预览正在等待确认。', 'today.progressSaved': '本次会话已保存食材清单和食谱步骤。', 'today.review': '查看并确认', 'today.resume': '继续烹饪', 'today.plan': '今晚计划', 'today.question': '今晚想吃\n什么？', 'today.found': '根据现有食材、家庭喜好和目标，我们找到了 {{count}} 个建议。', 'today.idea': '个建议', 'today.ideas': '个建议', 'today.choose': '选择今晚的餐点', 'today.ready': '厨房建议已准备好', 'today.glance': '一览', 'today.kitchen': '今日厨房', 'today.items': '项现有食材', 'today.low': '{{count}} 项库存偏低', 'today.stocked': '库存充足', 'today.mealIdeas': '个餐点建议', 'today.currentInventory': '基于当前库存', 'today.preferences': '项共同偏好', 'today.applied': '应用于每个建议', 'today.safety': '始终遵守安全要求和目标',
  'choose.back': '今日', 'choose.oneMatch': '1 个贴心建议', 'choose.matches': '{{count}} 个贴心建议', 'choose.title': '选择今晚的晚餐', 'choose.body': '每个选项都符合你的家庭档案，并说明了推荐理由。', 'choose.thinking': '思考中…', 'choose.refresh': '刷新建议', 'choose.model': '厨房助手带来了新建议。', 'choose.fallback': '模型暂不可用，当前显示可靠的备用建议。', 'choose.best': '最佳匹配', 'choose.minutes': '{{count}} 分钟', 'choose.why': '今晚为什么适合', 'choose.resume': '继续这道菜', 'choose.cook': '烹饪这道菜', 'choose.emptyTitle': '暂时没有餐点建议', 'choose.emptyBody': '建议准备好后会显示在这里，并附上清晰的家庭适配理由。', 'choose.respects': '每个选项都遵守：{{constraints}}。', 'difficulty.Easy': '简单', 'difficulty.Medium': '中等',
  'cook.back': '餐点选择', 'cook.mode': '烹饪模式', 'cook.summary': '{{minutes}} 分钟 · {{difficulty}} · {{count}} 人份', 'cook.readyLabel': '准备', 'cook.ingredients': '食材', 'cook.readyCount': '已准备 {{checked}}/{{total}}', 'cook.onHand': '已有', 'cook.need': '需要', 'cook.stepsLabel': '分步操作', 'cook.title': '开始烹饪', 'cook.stepOf': '第 {{step}} 步，共 {{total}} 步', 'cook.progress': '食谱进度：第 {{step}} 步，共 {{total}} 步', 'cook.previous': '上一步', 'cook.next': '下一步', 'cook.finish': '完成烹饪', 'cook.finished': '完成啦——准备上桌！',
  'confirm.complete': '晚餐完成', 'confirm.title': '做得好，厨房伙伴们！', 'confirm.body': '收拾之前，请告诉我们效果如何，并查看即将发生的变化。', 'confirm.feedback': '快速反馈', 'confirm.how': '{{meal}} 怎么样？', 'confirm.rating': '餐点评价', 'rating.loved': '很喜欢', 'rating.okay': '还可以', 'rating.not-for-us': '不适合我们', 'confirm.remember': '下次有什么要记住的吗？', 'common.optional': '可选', 'confirm.placeholder': '例如：大家都喜欢多加黄瓜…', 'confirm.preview': '库存预览', 'confirm.update': '将更新的内容', 'confirm.automatic': '自动', 'confirm.noChange': '根据食谱用量计算，确认前不会改变任何内容。', 'confirm.used': '使用 {{amount}}', 'confirm.back': '返回食谱', 'confirm.updating': '正在更新库存…', 'confirm.submit': '确认餐点并更新库存',
  'history.label': '你的餐桌', 'history.title': '餐点历史', 'history.body': '这些小记录会让下一次推荐更贴心。', 'history.favorites': '{{count}} 个家庭最爱', 'history.help': '你的反馈会帮助厨房助手改进未来建议。',
  'inventory.label': '你的厨房', 'inventory.title': '库存与档案', 'inventory.body': '请保持厨房助手所用信息准确。', 'inventory.saved': '已保存到厨房', 'inventory.guidance': '家庭指引', 'inventory.constraints': '安全限制', 'inventory.goals': '厨房目标', 'inventory.preferences': '饮食偏好', 'inventory.onePerLine': '每行一项', 'inventory.height': '身高（厘米）', 'inventory.heightAria': '{{name}} 的身高（厘米）', 'inventory.notes': '备注', 'inventory.notesAria': '{{name}} 的备注', 'inventory.saveProfile': '保存档案', 'inventory.addTitle': '添加食材', 'inventory.name': '名称', 'inventory.amount': '数量', 'inventory.unit': '单位', 'inventory.category': '分类', 'inventory.optionalDetails': '可选详情', 'inventory.count': '包装数量', 'inventory.countUnit': '包装单位', 'inventory.packages': '包', 'inventory.storage': '存放位置', 'inventory.pantryShelf': '食品柜', 'inventory.recordedOn': '记录日期', 'inventory.recorded': '记录于 {{date}}', 'inventory.add': '添加', 'inventory.search': '搜索库存', 'inventory.searchPlaceholder': '搜索食材', 'inventory.details': '{{name}} 的详情', 'inventory.decrease': '减少 {{name}}', 'inventory.increase': '增加 {{name}}', 'inventory.delete': '删除 {{name}}', 'inventory.low': '库存偏低', 'inventory.emptyTitle': '未找到食材', 'inventory.emptyBody': '请尝试其他搜索词或分类。',
  'category.All': '全部', 'category.Produce': '蔬菜', 'category.Fruit': '水果', 'category.Protein': '蛋白质', 'category.Prepared': '预制食品', 'category.Dairy': '乳制品', 'category.Pantry': '食品柜', 'category.Condiment': '调味品',
} as const
export default zhCN
