import { Check, Heart, Meh, RotateCcw, Sparkles, ThumbsDown } from 'lucide-react'
import { useI18n } from '../i18n'
import type { AppState, Meal, Rating } from '../types'
import { formatAmount, inventoryAfterMeal } from '../lib/store'

type Props = { meal: Meal; state: AppState; rating: Rating; note: string; onRatingChange: (rating: Rating) => void; onNoteChange: (note: string) => void; onConfirm: () => void; onBack: () => void; isConfirming: boolean; error?: string }
export function ConfirmMeal({ meal, state, rating, note, onRatingChange, onNoteChange, onConfirm, onBack, isConfirming, error }: Props) {
  const { t } = useI18n(); const after = inventoryAfterMeal(state, meal)
  const ratings = [{ id: 'loved', Icon: Heart }, { id: 'okay', Icon: Meh }, { id: 'not-for-us', Icon: ThumbsDown }] as const
  return <div className="page confirm-page"><header className="celebrate"><div className={`celebrate-art ${meal.accent}`}><Sparkles /></div><span className="eyebrow">{t('confirm.complete')}</span><h1>{t('confirm.title')}</h1><p>{t('confirm.body')}</p></header><div className="confirm-layout"><section className="panel feedback-panel"><span className="eyebrow">{t('confirm.feedback')}</span><h2>{t('confirm.how', { meal: meal.name })}</h2><div className="rating-grid" role="radiogroup" aria-label={t('confirm.rating')}>{ratings.map(({ id, Icon }) => <button role="radio" aria-checked={rating === id} key={id} className={rating === id ? 'selected' : ''} onClick={() => onRatingChange(id)}><Icon size={23} /><span>{t(`rating.${id}`)}</span></button>)}</div><label className="note-field">{t('confirm.remember')} <span>{t('common.optional')}</span><textarea value={note} onChange={(event) => onNoteChange(event.target.value)} placeholder={t('confirm.placeholder')} maxLength={180} /></label></section><section className="panel adjustment-panel"><div className="panel-heading"><div><span className="eyebrow">{t('confirm.preview')}</span><h2>{t('confirm.update')}</h2></div><span className="automatic"><RotateCcw size={13} /> {t('confirm.automatic')}</span></div><p className="muted">{t('confirm.noChange')}</p><div className="adjustment-list">{meal.ingredients.map((ingredient) => { const before = state.inventory.find((item) => item.id === ingredient.inventoryId); const next = after.find((item) => item.id === ingredient.inventoryId); return <div key={ingredient.inventoryId}><span><strong>{ingredient.name}</strong><small>{t('confirm.used', { amount: formatAmount(ingredient.amount, ingredient.unit) })}</small></span><span className="amount-change"><s>{before ? formatAmount(before.amount, before.unit) : '0'}</s><b>→</b><strong>{next ? formatAmount(next.amount, next.unit) : '0'}</strong></span></div> })}</div></section></div>{error && <p className="request-error" role="alert">{error}</p>}<div className="confirm-actions"><button className="secondary-button" onClick={onBack} disabled={isConfirming}>{t('confirm.back')}</button><button className="primary-button large" onClick={onConfirm} disabled={isConfirming}><Check size={18} /> {isConfirming ? t('confirm.updating') : t('confirm.submit')}</button></div></div>
}
