import type { AppState, Meal } from './types'

export const meals: Meal[] = [
  {
    id: 'miso-salmon',
    name: 'Miso-glazed salmon bowls',
    description: 'Caramelized salmon, sesame greens, brown rice, and a bright cucumber crunch.',
    reason: 'Uses the salmon and cucumber that need attention first, while supporting your high-protein goal.',
    emoji: '🍱',
    accent: 'coral',
    minutes: 30,
    difficulty: 'Easy',
    tags: ['High protein', 'Uses 4 pantry items'],
    ingredients: [
      { inventoryId: 'salmon', name: 'Salmon fillets', amount: 2, unit: 'fillets' },
      { inventoryId: 'rice', name: 'Brown rice', amount: 1, unit: 'cup' },
      { inventoryId: 'cucumber', name: 'Cucumber', amount: 1, unit: '' },
      { inventoryId: 'spinach', name: 'Baby spinach', amount: 3, unit: 'cups' },
      { inventoryId: 'miso', name: 'White miso', amount: 2, unit: 'tbsp' },
    ],
    steps: [
      'Start the brown rice according to the package instructions.',
      'Whisk miso with a splash of warm water. Brush over the salmon.',
      'Roast salmon at 220°C / 425°F for 10–12 minutes, until it flakes easily.',
      'Quick-sauté the spinach and thinly slice the cucumber.',
      'Build the bowls with rice, greens, salmon, and cucumber. Spoon over any extra glaze.',
    ],
  },
  {
    id: 'chickpea-pasta',
    name: 'Creamy lemon chickpea pasta',
    description: 'Silky lemon sauce, chickpeas, spinach, and plenty of fresh herbs.',
    reason: 'A low-effort pantry dinner with no dairy, peanuts, or complicated prep — ideal for a busy night.',
    emoji: '🍋',
    accent: 'yellow',
    minutes: 22,
    difficulty: 'Easy',
    tags: ['Plant-powered', 'One pot'],
    ingredients: [
      { inventoryId: 'pasta', name: 'Whole-wheat pasta', amount: 300, unit: 'g' },
      { inventoryId: 'chickpeas', name: 'Chickpeas', amount: 1, unit: 'can' },
      { inventoryId: 'spinach', name: 'Baby spinach', amount: 3, unit: 'cups' },
      { inventoryId: 'lemon', name: 'Lemon', amount: 1, unit: '' },
    ],
    steps: [
      'Boil the pasta in well-salted water. Reserve a mug of cooking water.',
      'Drain and rinse the chickpeas, then warm them in the empty pot.',
      'Return pasta to the pot with spinach, lemon zest, and juice.',
      'Add pasta water a little at a time and toss until glossy and creamy.',
      'Season generously and finish with herbs or chili flakes, if you like.',
    ],
  },
  {
    id: 'taco-tray',
    name: 'Smoky chicken taco tray',
    description: 'Sheet-pan chicken and peppers with warm tortillas and avocado-lime salsa.',
    reason: 'A playful, family-style option for Friday that keeps every topping customizable at the table.',
    emoji: '🌮',
    accent: 'green',
    minutes: 35,
    difficulty: 'Medium',
    tags: ['Family favorite', 'Customizable'],
    ingredients: [
      { inventoryId: 'chicken', name: 'Chicken breast', amount: 450, unit: 'g' },
      { inventoryId: 'peppers', name: 'Bell peppers', amount: 2, unit: '' },
      { inventoryId: 'tortillas', name: 'Corn tortillas', amount: 8, unit: '' },
      { inventoryId: 'avocado', name: 'Avocado', amount: 1, unit: '' },
      { inventoryId: 'lime', name: 'Lime', amount: 1, unit: '' },
    ],
    steps: [
      'Heat the oven to 220°C / 425°F and slice the chicken and peppers.',
      'Toss chicken and peppers with oil, smoked paprika, cumin, and salt.',
      'Roast on a sheet pan for 18–20 minutes, stirring halfway.',
      'Mash avocado with lime juice and a pinch of salt.',
      'Warm the tortillas and let everyone build their own tacos.',
    ],
  },
]

export const initialState: AppState = {
  household: {
    name: 'Shared household',
    members: [
      { id: 'member-one', name: 'Member one', initials: 'M1', heightCm: 170, notes: ['Prefers smaller portions'] },
      { id: 'member-two', name: 'Member two', initials: 'M2' },
      { id: 'member-three', name: 'Member three', initials: 'M3' },
    ],
    constraints: ['Keep ingredients separate'],
    goals: ['High protein', 'Less food waste'],
    preferences: ['Quick weekday meals'],
  },
  meals,
  selectedMealId: null,
  inventory: [
    { id: 'salmon', name: 'Salmon fillets', amount: 2, unit: 'fillets', category: 'Protein', lowAt: 1 },
    { id: 'chicken', name: 'Chicken breast', amount: 450, unit: 'g', category: 'Protein', lowAt: 300 },
    { id: 'rice', name: 'Brown rice', amount: 3, unit: 'cups', category: 'Pantry', lowAt: 1, count: 1, countUnit: 'bag', storage: 'Pantry', recordedOn: '2026-09-20', notes: 'Opened' },
    { id: 'pasta', name: 'Whole-wheat pasta', amount: 500, unit: 'g', category: 'Pantry', lowAt: 200 },
    { id: 'chickpeas', name: 'Chickpeas', amount: 2, unit: 'cans', category: 'Pantry', lowAt: 1 },
    { id: 'miso', name: 'White miso', amount: 8, unit: 'tbsp', category: 'Pantry', lowAt: 2 },
    { id: 'cucumber', name: 'Cucumber', amount: 1, unit: '', category: 'Produce', lowAt: 1 },
    { id: 'spinach', name: 'Baby spinach', amount: 6, unit: 'cups', category: 'Produce', lowAt: 2 },
    { id: 'lemon', name: 'Lemon', amount: 2, unit: '', category: 'Produce', lowAt: 1 },
    { id: 'peppers', name: 'Bell peppers', amount: 3, unit: '', category: 'Produce', lowAt: 1 },
    { id: 'avocado', name: 'Avocado', amount: 2, unit: '', category: 'Produce', lowAt: 1 },
    { id: 'lime', name: 'Lime', amount: 2, unit: '', category: 'Produce', lowAt: 1 },
    { id: 'tortillas', name: 'Corn tortillas', amount: 12, unit: '', category: 'Pantry', lowAt: 4 },
  ],
  history: [
    { id: 'history-1', mealId: 'tomato-soup', mealName: 'Roasted tomato soup', emoji: '🍅', cookedAt: '2026-09-24T18:30:00.000Z', rating: 'loved', note: 'Great with extra basil.' },
    { id: 'history-2', mealId: 'veggie-rice', mealName: 'Ginger vegetable fried rice', emoji: '🥕', cookedAt: '2026-09-21T18:30:00.000Z', rating: 'okay', note: 'Add more ginger next time.' },
  ],
}
